### ISSUE TITLE
[Blacklisted]  Issue # 13 - blacklisted hok files with no data in January 2017

### ISSUE THREAD

**Issue by mts299** [SuperDARN/DDWG#34] opened 2020-07-13 17:26 UTC
# Proposed File(s)
11-8 UT on Jan 12-Jan 13
Jan 27 

## Affiliated Mirror
- [X] BAS
- [X] USAK
- [X] VT (holding institute) 

## Reason
Hello DDWG,

We've got a list of Hokkaido East files from January 2017 that should be removed from your data directories. Please check out this message from Nozomu regarding the files:

Yes, the Hokkaido East radar became faulty around 11 UT on Jan 12 owing
to the loss of blanking signal connection. Then we fixed it slightly
before 8 UT on
Jan 27, by detaching the blanking signal cable from the Hokkaido East
radar.
Later we fixed the cable connection and recovered both the Hokkaido East
and West radars. I agree to remove the data file during this faulty
operation
period.

See attached file for the blacklisted files. They have been removed from the SuperDARN globus mirror.
As always if you have questions/comments please reply here and we'll discuss. Issue will be closed in time if there are no questions or comments.

Regards,
Kevin Krieger 

## Tasks 
- [ ] Remove RAWACF files from the mirrors 
- [ ] Add to blacklisted list 
- [ ] Reprocess and upper data products

**Comment by kevinkrieger** [comment] 2020-07-16 02:10
Duplicate of https://github.com/SuperDARN/DDWG/issues/8

**Closed as completed by kevinkrieger** 2020-07-16 02:10 UTC
